[build]
  publish = "."
  command = "node build-env.js"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "env-config.js"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"